// Generated by typeDiagram from models.td. DO NOT EDIT.

export interface AgentIdentity {
  agentName: string;
  registeredAt: number;
  lastActive: number;
}

export interface AgentRegistration {
  agentName: string;
  agentKey: string;
}

export interface FileLock {
  filePath: string;
  agentName: string;
  acquiredAt: number;
  expiresAt: number;
  reason: string | undefined;
  version: number;
}

export interface LockResult {
  acquired: boolean;
  lock: FileLock | undefined;
  error: string | undefined;
}

export interface Message {
  id: string;
  fromAgent: string;
  toAgent: string;
  content: string;
  createdAt: number;
  readAt: number | undefined;
}

export interface AgentPlan {
  agentName: string;
  goal: string;
  currentTask: string;
  updatedAt: number;
}

export interface DbError {
  code: string;
  message: string;
}
