// Generated by typeDiagram from models.td. DO NOT EDIT.

export interface AgentIdentity {
  readonly agentName: string;
  readonly registeredAt: number;
  readonly lastActive: number;
}

export interface AgentRegistration {
  readonly agentName: string;
  readonly agentKey: string;
}

export interface FileLock {
  readonly filePath: string;
  readonly agentName: string;
  readonly acquiredAt: number;
  readonly expiresAt: number;
  readonly reason: string | null;
  readonly version: number;
}

export interface LockResult {
  readonly acquired: boolean;
  readonly lock: FileLock | null;
  readonly error: string | null;
}

export interface Message {
  readonly id: string;
  readonly fromAgent: string;
  readonly toAgent: string;
  readonly content: string;
  readonly createdAt: number;
  readonly readAt: number | null;
}

export interface AgentPlan {
  readonly agentName: string;
  readonly goal: string;
  readonly currentTask: string;
  readonly updatedAt: number;
}

export interface DbError {
  readonly code: string;
  readonly message: string;
}
