// Generated by tmc_codegen. DO NOT EDIT.

// Agent identity (public info only - no key).
export interface AgentIdentity {
  readonly agentName: string;
  readonly registeredAt: number;
  readonly lastActive: number;
}

// Agent registration result (includes secret key).
export interface AgentRegistration {
  readonly agentName: string;
  readonly agentKey: string;
}

// File lock info.
export interface FileLock {
  readonly filePath: string;
  readonly agentName: string;
  readonly acquiredAt: number;
  readonly expiresAt: number;
  readonly reason: string | null;
  readonly version: number;
}

// Lock acquisition result.
export interface LockResult {
  readonly acquired: boolean;
  readonly lock: FileLock | null;
  readonly error: string | null;
}

// Inter-agent message.
export interface Message {
  readonly id: string;
  readonly fromAgent: string;
  readonly toAgent: string;
  readonly content: string;
  readonly createdAt: number;
  readonly readAt: number | null;
}

// Agent plan (what they're doing and why).
export interface AgentPlan {
  readonly agentName: string;
  readonly goal: string;
  readonly currentTask: string;
  readonly updatedAt: number;
}

// Database error.
export interface DbError {
  readonly code: string;
  readonly message: string;
}

function stringField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): string {
  const value: unknown = record[key];
  return typeof value === 'string' ? value : '';
}

function numberField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): number {
  const value: unknown = record[key];
  return typeof value === 'number' ? value : 0;
}

function boolField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): boolean {
  const value: unknown = record[key];
  return typeof value === 'boolean' ? value : false;
}

function nullableStringField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): string | null {
  const value: unknown = record[key];
  return typeof value === 'string' ? value : null;
}

function nullableNumberField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): number | null {
  const value: unknown = record[key];
  return typeof value === 'number' ? value : null;
}

function nullableBoolField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): boolean | null {
  const value: unknown = record[key];
  return typeof value === 'boolean' ? value : null;
}

function isRecord(
  value: unknown,
): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function parseArray<T>(
  data: unknown,
  mapper: (raw: Readonly<Record<string, unknown>>) => T,
): T[] {
  if (!Array.isArray(data)) {
    return [];
  }
  return data
    .filter((item: unknown): item is Record<string, unknown> => isRecord(item))
    .map(mapper);
}

export function parseAgentIdentity(
  raw: Readonly<Record<string, unknown>>,
): AgentIdentity {
  return {
    agentName: stringField(raw, 'agent_name'),
    registeredAt: numberField(raw, 'registered_at'),
    lastActive: numberField(raw, 'last_active'),
  };
}

export function parseAgentRegistration(
  raw: Readonly<Record<string, unknown>>,
): AgentRegistration {
  return {
    agentName: stringField(raw, 'agent_name'),
    agentKey: stringField(raw, 'agent_key'),
  };
}

export function parseFileLock(
  raw: Readonly<Record<string, unknown>>,
): FileLock {
  return {
    filePath: stringField(raw, 'file_path'),
    agentName: stringField(raw, 'agent_name'),
    acquiredAt: numberField(raw, 'acquired_at'),
    expiresAt: numberField(raw, 'expires_at'),
    reason: nullableStringField(raw, 'reason'),
    version: numberField(raw, 'version'),
  };
}

export function parseLockResult(
  raw: Readonly<Record<string, unknown>>,
): LockResult {
  return {
    acquired: boolField(raw, 'acquired'),
    lock: isRecord(raw['lock']) ? parseFileLock(raw['lock'] as Record<string, unknown>) : null,
    error: nullableStringField(raw, 'error'),
  };
}

export function parseMessage(
  raw: Readonly<Record<string, unknown>>,
): Message {
  return {
    id: stringField(raw, 'id'),
    fromAgent: stringField(raw, 'from_agent'),
    toAgent: stringField(raw, 'to_agent'),
    content: stringField(raw, 'content'),
    createdAt: numberField(raw, 'created_at'),
    readAt: nullableNumberField(raw, 'read_at'),
  };
}

export function parseAgentPlan(
  raw: Readonly<Record<string, unknown>>,
): AgentPlan {
  return {
    agentName: stringField(raw, 'agent_name'),
    goal: stringField(raw, 'goal'),
    currentTask: stringField(raw, 'current_task'),
    updatedAt: numberField(raw, 'updated_at'),
  };
}

export function parseDbError(
  raw: Readonly<Record<string, unknown>>,
): DbError {
  return {
    code: stringField(raw, 'code'),
    message: stringField(raw, 'message'),
  };
}

