/// Emit Dart typedef records with toJson/fromJson from model definitions.
library;

import 'package:tmc_codegen/src/types.dart';

/// Generated file header with lint ignores for generated code.
const _header = '/// Generated by tmc_codegen. DO NOT EDIT.\n'
    '// ignore_for_file: lines_longer_than_80_chars\n'
    'library;\n';

/// Generate complete Dart file from a schema.
String emitDart(Schema schema) {
  final buf = StringBuffer(_header)..writeln();

  for (final model in schema.models) {
    _emitTypedef(buf, model);
    buf.writeln();
    _emitToJson(buf, model);
    buf.writeln();
    _emitFromJson(buf, model);
    buf.writeln();
  }

  final result = buf.toString().trimRight();
  return '$result\n';
}

void _emitTypedef(StringBuffer buf, ModelDef model) {
  if (model.description != null) {
    buf.writeln('/// ${model.description}');
  }
  buf
    ..writeln('typedef ${model.name} = ({')
    ..writeAll(
      model.fields.map((f) {
        final dartType = _dartType(f.type, f.required);
        return '  $dartType ${f.name},\n';
      }),
    )
    ..writeln('});');
}

void _emitToJson(StringBuffer buf, ModelDef model) {
  final paramName = _lowerFirst(model.name);
  final fnName = '${_lowerFirst(model.name)}ToJson';
  buf
    ..writeln('/// Serialize ${model.name} to a JSON-compatible map.')
    ..writeln('Map<String, Object?> $fnName(${model.name} $paramName) => {');

  for (final field in model.fields) {
    final snakeKey = toSnakeCase(field.name);
    final accessor = '$paramName.${field.name}';
    if (!field.required) {
      switch (field.type) {
        case StringField() ||
             IntField() ||
             DoubleField() ||
             BoolField():
          buf.writeln("  '$snakeKey': ?$accessor,");
        case ArrayField() || RefField():
          final valueExpr = _mapValueExprNullable(accessor, field.type);
          buf.writeln(
            "  if ($accessor case final v?) '$snakeKey': $valueExpr,",
          );
      }
    } else {
      final valueExpr = _mapValueExpr(accessor, field.type);
      buf.writeln("  '$snakeKey': $valueExpr,");
    }
  }

  buf.writeln('};\n');
}

void _emitFromJson(StringBuffer buf, ModelDef model) {
  final fnName = '${_lowerFirst(model.name)}FromJson';
  buf
    ..writeln('/// Deserialize ${model.name} from a JSON map.')
    ..writeln('${model.name} $fnName(Map<String, Object?> json) => (');

  for (final field in model.fields) {
    final snakeKey = toSnakeCase(field.name);
    final expr = _fromJsonExpr("json['$snakeKey']", field.type, field.required);
    buf.writeln('  ${field.name}: $expr,');
  }

  buf.writeln(');');
}

// -- Helpers --

String _dartType(FieldType type, bool isRequired) {
  final base = switch (type) {
    StringField() => 'String',
    IntField() => 'int',
    DoubleField() => 'double',
    BoolField() => 'bool',
    ArrayField(:final items) => 'List<${_dartType(items, true)}>',
    RefField(:final modelName) => modelName,
  };
  return isRequired ? base : '$base?';
}

String _mapValueExpr(String accessor, FieldType type) =>
    switch (type) {
      StringField() || IntField() || DoubleField() || BoolField() =>
        accessor,
      ArrayField(:final items) =>
        '$accessor.map((e) => ${_mapValueExpr("e", items)}).toList()',
      RefField(:final modelName) =>
        '${_lowerFirst(modelName)}ToJson($accessor)',
    };

String _mapValueExprNullable(
  String accessor,
  FieldType type,
) => switch (type) {
  StringField() || IntField() || DoubleField() || BoolField() => 'v',
  ArrayField(:final items) =>
    'v.map((e) => ${_mapValueExpr("e", items)}).toList()',
  RefField(:final modelName) =>
    '${_lowerFirst(modelName)}ToJson(v)',
};

String _fromJsonExpr(String accessor, FieldType type, bool isRequired) {
  if (!isRequired) return _nullableFromJson(accessor, type);

  return switch (type) {
    StringField() =>
      "switch ($accessor) { final String v => v, _ => '' }",
    IntField() => 'switch ($accessor) { final int v => v, _ => 0 }',
    DoubleField() =>
      'switch ($accessor) { final double v => v, _ => 0.0 }',
    BoolField() =>
      'switch ($accessor) { final bool v => v, _ => false }',
    ArrayField(:final items) => _fromJsonArray(accessor, items),
    RefField(:final modelName) =>
      'switch ($accessor) '
      '{ final Map<String, Object?> v => '
      '${_lowerFirst(modelName)}FromJson(v), '
      "_ => throw FormatException('expected $modelName') }",
  };
}

String _nullableFromJson(String accessor, FieldType type) =>
    switch (type) {
      StringField() =>
        'switch ($accessor) { final String v => v, _ => null }',
      IntField() =>
        'switch ($accessor) { final int v => v, _ => null }',
      DoubleField() =>
        'switch ($accessor) { final double v => v, _ => null }',
      BoolField() =>
        'switch ($accessor) { final bool v => v, _ => null }',
      ArrayField(:final items) =>
        'switch ($accessor) { final List<Object?> v => '
        '${_fromJsonArrayBody("v", items)}, _ => null }',
      RefField(:final modelName) =>
        'switch ($accessor) { final Map<String, Object?> v => '
        '${_lowerFirst(modelName)}FromJson(v), _ => null }',
    };

String _fromJsonArray(String accessor, FieldType items) =>
    'switch ($accessor) { '
    'final List<Object?> v => ${_fromJsonArrayBody("v", items)}, '
    '_ => <${_dartType(items, true)}>[] }';

String _fromJsonArrayBody(String listVar, FieldType items) => switch (items) {
  StringField() => '$listVar.whereType<String>().toList()',
  IntField() => '$listVar.whereType<int>().toList()',
  DoubleField() => '$listVar.whereType<double>().toList()',
  BoolField() => '$listVar.whereType<bool>().toList()',
  RefField(:final modelName) =>
    '$listVar.whereType<Map<String, Object?>>().map('
    '${_lowerFirst(modelName)}FromJson).toList()',
  ArrayField() => throw UnimplementedError('nested arrays'),
};

String _lowerFirst(String s) =>
    s.isEmpty ? s : '${s[0].toLowerCase()}${s.substring(1)}';
