/// Emit TypeScript readonly interfaces with fromJson helpers.
library;

import 'package:tmc_codegen/src/types.dart';

/// Generated file header.
const _header = '// Generated by tmc_codegen. DO NOT EDIT.\n'
    '/* eslint-disable @typescript-eslint/no-unused-vars */\n';

/// Generate complete TypeScript file from a schema.
String emitTypeScript(Schema schema) {
  final buf = StringBuffer(_header)..writeln();

  for (final model in schema.models) {
    _emitInterface(buf, model);
    buf.writeln();
  }

  _emitFieldHelpers(buf);
  buf.writeln();

  for (final model in schema.models) {
    _emitFromJson(buf, model);
    buf.writeln();
  }

  return buf.toString();
}

void _emitInterface(StringBuffer buf, ModelDef model) {
  if (model.description != null) {
    buf.writeln('// ${model.description}');
  }
  buf.writeln('export interface ${model.name} {');
  for (final field in model.fields) {
    final tsType = _tsType(field.type, field.required);
    buf.writeln('  readonly ${field.name}: $tsType;');
  }
  buf.writeln('}');
}

void _emitFieldHelpers(StringBuffer buf) {
  buf
    ..writeln(_stringFieldFn)
    ..writeln()
    ..writeln(_numberFieldFn)
    ..writeln()
    ..writeln(_boolFieldFn)
    ..writeln()
    ..writeln(_nullableStringFieldFn)
    ..writeln()
    ..writeln(_nullableNumberFieldFn)
    ..writeln()
    ..writeln(_nullableBoolFieldFn)
    ..writeln()
    ..writeln(_isRecordFn)
    ..writeln()
    ..writeln(_parseArrayFn);
}

void _emitFromJson(StringBuffer buf, ModelDef model) {
  final fnName = 'parse${model.name}';
  buf
    ..writeln('export function $fnName(')
    ..writeln('  raw: Readonly<Record<string, unknown>>,')
    ..writeln('): ${model.name} {')
    ..writeln('  return {');

  for (final field in model.fields) {
    final snakeKey = toSnakeCase(field.name);
    final expr = _fromJsonExpr(snakeKey, field.type, field.required);
    buf.writeln('    ${field.name}: $expr,');
  }

  buf
    ..writeln('  };')
    ..writeln('}');
}

// -- Type mapping --

String _tsType(FieldType type, bool isRequired) {
  final base = switch (type) {
    StringField() => 'string',
    IntField() || DoubleField() => 'number',
    BoolField() => 'boolean',
    ArrayField(:final items) => 'readonly ${_tsType(items, true)}[]',
    RefField(:final modelName) => modelName,
  };
  return isRequired ? base : '$base | null';
}

// -- fromJson expressions --

String _fromJsonExpr(String key, FieldType type, bool isRequired) {
  if (!isRequired) return _nullableFromJson(key, type);

  return switch (type) {
    StringField() => "stringField(raw, '$key')",
    IntField() || DoubleField() => "numberField(raw, '$key')",
    BoolField() => "boolField(raw, '$key')",
    ArrayField(:final items) => _fromJsonArray(key, items),
    RefField(:final modelName) =>
      "isRecord(raw['$key']) "
          "? parse$modelName(raw['$key'] as Record<string, unknown>) "
          ': ({} as $modelName)',
  };
}

String _nullableFromJson(String key, FieldType type) => switch (type) {
  StringField() => "nullableStringField(raw, '$key')",
  IntField() || DoubleField() => "nullableNumberField(raw, '$key')",
  BoolField() => "nullableBoolField(raw, '$key')",
  ArrayField(:final items) => _nullableFromJsonArray(key, items),
  RefField(:final modelName) =>
    "isRecord(raw['$key']) "
        "? parse$modelName(raw['$key'] as Record<string, unknown>) "
        ': null',
};

String _fromJsonArray(String key, FieldType items) => switch (items) {
  StringField() ||
  IntField() ||
  DoubleField() ||
  BoolField() => "parseArray(raw['$key'], (v) => v as ${_tsType(items, true)})",
  RefField(:final modelName) => "parseArray(raw['$key'], parse$modelName)",
  ArrayField() => throw UnimplementedError('nested arrays'),
};

String _nullableFromJsonArray(String key, FieldType items) =>
    "Array.isArray(raw['$key']) ? ${_fromJsonArray(key, items)} : null";

// -- Helper function source --

const _stringFieldFn = '''
export function stringField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): string {
  const value: unknown = record[key];
  return typeof value === 'string' ? value : '';
}''';

const _numberFieldFn = '''
export function numberField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): number {
  const value: unknown = record[key];
  return typeof value === 'number' ? value : 0;
}''';

const _boolFieldFn = '''
export function boolField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): boolean {
  const value: unknown = record[key];
  return typeof value === 'boolean' ? value : false;
}''';

const _nullableStringFieldFn = '''
export function nullableStringField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): string | null {
  const value: unknown = record[key];
  return typeof value === 'string' ? value : null;
}''';

const _nullableNumberFieldFn = '''
export function nullableNumberField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): number | null {
  const value: unknown = record[key];
  return typeof value === 'number' ? value : null;
}''';

const _nullableBoolFieldFn = '''
export function nullableBoolField(
  record: Readonly<Record<string, unknown>>,
  key: string,
): boolean | null {
  const value: unknown = record[key];
  return typeof value === 'boolean' ? value : null;
}''';

const _isRecordFn = '''
function isRecord(
  value: unknown,
): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}''';

const _parseArrayFn = '''
function parseArray<T>(
  data: unknown,
  mapper: (raw: Readonly<Record<string, unknown>>) => T,
): T[] {
  if (!Array.isArray(data)) {
    return [];
  }
  return data
    .filter((item: unknown): item is Record<string, unknown> => isRecord(item))
    .map(mapper);
}''';
