/// Generated by tmc_codegen. DO NOT EDIT.
// ignore_for_file: lines_longer_than_80_chars
library;

/// Agent identity (public info only - no key).
typedef AgentIdentity = ({
  String agentName,
  int registeredAt,
  int lastActive,
});

/// Serialize AgentIdentity to a JSON-compatible map.
Map<String, Object?> agentIdentityToJson(AgentIdentity agentIdentity) => {
  'agent_name': agentIdentity.agentName,
  'registered_at': agentIdentity.registeredAt,
  'last_active': agentIdentity.lastActive,
};


/// Deserialize AgentIdentity from a JSON map.
AgentIdentity agentIdentityFromJson(Map<String, Object?> json) => (
  agentName: switch (json['agent_name']) { final String v => v, _ => '' },
  registeredAt: switch (json['registered_at']) { final int v => v, _ => 0 },
  lastActive: switch (json['last_active']) { final int v => v, _ => 0 },
);

/// Agent registration result (includes secret key).
typedef AgentRegistration = ({
  String agentName,
  String agentKey,
});

/// Serialize AgentRegistration to a JSON-compatible map.
Map<String, Object?> agentRegistrationToJson(AgentRegistration agentRegistration) => {
  'agent_name': agentRegistration.agentName,
  'agent_key': agentRegistration.agentKey,
};


/// Deserialize AgentRegistration from a JSON map.
AgentRegistration agentRegistrationFromJson(Map<String, Object?> json) => (
  agentName: switch (json['agent_name']) { final String v => v, _ => '' },
  agentKey: switch (json['agent_key']) { final String v => v, _ => '' },
);

/// File lock info.
typedef FileLock = ({
  String filePath,
  String agentName,
  int acquiredAt,
  int expiresAt,
  String? reason,
  int version,
});

/// Serialize FileLock to a JSON-compatible map.
Map<String, Object?> fileLockToJson(FileLock fileLock) => {
  'file_path': fileLock.filePath,
  'agent_name': fileLock.agentName,
  'acquired_at': fileLock.acquiredAt,
  'expires_at': fileLock.expiresAt,
  'reason': ?fileLock.reason,
  'version': fileLock.version,
};


/// Deserialize FileLock from a JSON map.
FileLock fileLockFromJson(Map<String, Object?> json) => (
  filePath: switch (json['file_path']) { final String v => v, _ => '' },
  agentName: switch (json['agent_name']) { final String v => v, _ => '' },
  acquiredAt: switch (json['acquired_at']) { final int v => v, _ => 0 },
  expiresAt: switch (json['expires_at']) { final int v => v, _ => 0 },
  reason: switch (json['reason']) { final String v => v, _ => null },
  version: switch (json['version']) { final int v => v, _ => 0 },
);

/// Lock acquisition result.
typedef LockResult = ({
  bool acquired,
  FileLock? lock,
  String? error,
});

/// Serialize LockResult to a JSON-compatible map.
Map<String, Object?> lockResultToJson(LockResult lockResult) => {
  'acquired': lockResult.acquired,
  if (lockResult.lock case final v?) 'lock': fileLockToJson(v),
  'error': ?lockResult.error,
};


/// Deserialize LockResult from a JSON map.
LockResult lockResultFromJson(Map<String, Object?> json) => (
  acquired: switch (json['acquired']) { final bool v => v, _ => false },
  lock: switch (json['lock']) { final Map<String, Object?> v => fileLockFromJson(v), _ => null },
  error: switch (json['error']) { final String v => v, _ => null },
);

/// Inter-agent message.
typedef Message = ({
  String id,
  String fromAgent,
  String toAgent,
  String content,
  int createdAt,
  int? readAt,
});

/// Serialize Message to a JSON-compatible map.
Map<String, Object?> messageToJson(Message message) => {
  'id': message.id,
  'from_agent': message.fromAgent,
  'to_agent': message.toAgent,
  'content': message.content,
  'created_at': message.createdAt,
  'read_at': ?message.readAt,
};


/// Deserialize Message from a JSON map.
Message messageFromJson(Map<String, Object?> json) => (
  id: switch (json['id']) { final String v => v, _ => '' },
  fromAgent: switch (json['from_agent']) { final String v => v, _ => '' },
  toAgent: switch (json['to_agent']) { final String v => v, _ => '' },
  content: switch (json['content']) { final String v => v, _ => '' },
  createdAt: switch (json['created_at']) { final int v => v, _ => 0 },
  readAt: switch (json['read_at']) { final int v => v, _ => null },
);

/// Agent plan (what they're doing and why).
typedef AgentPlan = ({
  String agentName,
  String goal,
  String currentTask,
  int updatedAt,
});

/// Serialize AgentPlan to a JSON-compatible map.
Map<String, Object?> agentPlanToJson(AgentPlan agentPlan) => {
  'agent_name': agentPlan.agentName,
  'goal': agentPlan.goal,
  'current_task': agentPlan.currentTask,
  'updated_at': agentPlan.updatedAt,
};


/// Deserialize AgentPlan from a JSON map.
AgentPlan agentPlanFromJson(Map<String, Object?> json) => (
  agentName: switch (json['agent_name']) { final String v => v, _ => '' },
  goal: switch (json['goal']) { final String v => v, _ => '' },
  currentTask: switch (json['current_task']) { final String v => v, _ => '' },
  updatedAt: switch (json['updated_at']) { final int v => v, _ => 0 },
);

/// Database error.
typedef DbError = ({
  String code,
  String message,
});

/// Serialize DbError to a JSON-compatible map.
Map<String, Object?> dbErrorToJson(DbError dbError) => {
  'code': dbError.code,
  'message': dbError.message,
};


/// Deserialize DbError from a JSON map.
DbError dbErrorFromJson(Map<String, Object?> json) => (
  code: switch (json['code']) { final String v => v, _ => '' },
  message: switch (json['message']) { final String v => v, _ => '' },
);
