#!/bin/bash
# Generate TypeScript model interfaces from the TypeDiagram source.
# Source of truth: too_many_cooks_vscode_extension/src/state/models.td
# Tool: typeDiagram (https://typediagram.dev) — `typediagram --to typescript`.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

STATE_DIR="$ROOT_DIR/too_many_cooks_vscode_extension/src/state"
TD_SOURCE="$STATE_DIR/models.td"
TS_OUT="$STATE_DIR/types.gen.ts"
BANNER="// Generated by typeDiagram from models.td. DO NOT EDIT."

echo "Generating $TS_OUT from $TD_SOURCE via typeDiagram..."
{
  echo "$BANNER"
  echo ""
  npx --yes typediagram --to typescript "$TD_SOURCE"
} > "$TS_OUT"

echo "Done. TypeScript: $TS_OUT"
